#include<stdio.h>
#include<stdlib.h> // atoi()
#include<string.h> // strcpy(),strcmp()
#include<math.h>   //ceil()
#include "pgpg.h"

void generate_pg_lcell(vd,dev)
struct vhdl_description* vd;
char* dev; // device family name
{
  int ie;
  int iflag;
  int j;
  char dev_name[STRLEN];
  strcpy(dev_name,dev);
  ie = (*vd).ie;
  sprintf((*vd).sde[ie], "\n" );ie++;
  sprintf((*vd).sde[ie], "--+-------------------------------+\n");ie++;
  sprintf((*vd).sde[ie], "--| PG_LCELL/PG_LCELL_ARI         |\n");ie++;
  sprintf((*vd).sde[ie], "--| Multidevice Logic Cell Module |.GKey:hYj8zgUkjgdkfhB3ozXM\n");ie++;
  iflag=0;
  for(j=0;j<(ie-1);j++){
    if(strcmp((*vd).sde[ie-1],(*vd).sde[j])==0) iflag=1;
  }
  if(iflag !=0) return;
  sprintf((*vd).sde[ie], "--| 2003/10/31                    |\n");ie++;
  sprintf((*vd).sde[ie], "--|            by Tsuyoshi Hamada |\n");ie++;
  sprintf((*vd).sde[ie], "--+-------------------------------+\n");ie++;

  // Logic Cell in the NORMAL MODE
  sprintf((*vd).sde[ie], "--+-------------+----------+\n");ie++;
  sprintf((*vd).sde[ie], "--| x3,x2,x1,x0 |    z     |\n");ie++;
  sprintf((*vd).sde[ie], "--+-------------+----------+\n");ie++;
  sprintf((*vd).sde[ie], "--|  0, 0, 0, 0 | MASK(0)  |\n");ie++;
  sprintf((*vd).sde[ie], "--|  0, 0, 0, 1 | MASK(1)  |\n");ie++;
  sprintf((*vd).sde[ie], "--|  0, 0, 1, 0 | MASK(2)  |\n");ie++;
  sprintf((*vd).sde[ie], "--|  0, 0, 1, 1 | MASK(3)  |\n");ie++;
  sprintf((*vd).sde[ie], "--|  0, 1, 0, 0 | MASK(4)  |\n");ie++;
  sprintf((*vd).sde[ie], "--|  0, 1, 0, 1 | MASK(5)  |\n");ie++;
  sprintf((*vd).sde[ie], "--|  .......... | .......  |\n");ie++;
  sprintf((*vd).sde[ie], "--|  1, 1, 1, 1 | MASK(16) |\n");ie++;
  sprintf((*vd).sde[ie], "--+-------------+----------+\n");ie++;
  sprintf((*vd).sde[ie], "library ieee;\n" );ie++;
  sprintf((*vd).sde[ie], "use ieee.std_logic_1164.all;\n" );ie++;
  sprintf((*vd).sde[ie], "library wysiwyg;\n" );ie++;
  sprintf((*vd).sde[ie], "use wysiwyg.%s_components.all;\n",dev_name);ie++;
  sprintf((*vd).sde[ie], "\n" );ie++;
  sprintf((*vd).sde[ie], "entity pg_lcell is\n");ie++;
  sprintf((*vd).sde[ie], "  generic(MASK: string  := \"ffff\";\n");ie++;
  sprintf((*vd).sde[ie], "            FF: integer := 0);\n");ie++;
  sprintf((*vd).sde[ie], "    port(x : in std_logic_vector(3 downto 0);\n");ie++;
  sprintf((*vd).sde[ie], "         z : out std_logic;\n");ie++;
  sprintf((*vd).sde[ie], "         clk : in std_logic);\n");ie++;
  sprintf((*vd).sde[ie], "end pg_lcell;\n");ie++;
  sprintf((*vd).sde[ie], "\n" );ie++;
  sprintf((*vd).sde[ie], "architecture rtl of pg_lcell is\n");ie++;
  sprintf((*vd).sde[ie], "\n" );ie++;
  if((strcmp(dev_name,"apex20k")==0)||(strcmp(dev_name,"apex20ke")==0)){
    sprintf((*vd).sde[ie], "component %s_lcell\n",dev_name);ie++;
    sprintf((*vd).sde[ie], "  generic (operation_mode  : string := \"normal\";\n");ie++;
    sprintf((*vd).sde[ie], "    output_mode : string := \"comb_and_reg\";\n");ie++;
    sprintf((*vd).sde[ie], "    packed_mode : string := \"false\";\n");ie++;
    sprintf((*vd).sde[ie], "    lut_mask    : string := \"0000\";\n");ie++;
    sprintf((*vd).sde[ie], "    power_up : string := \"low\";\n");ie++;
    sprintf((*vd).sde[ie], "    cin_used : string := \"false\");\n");ie++;
    sprintf((*vd).sde[ie], "  port (clk  : in std_logic := '0';\n");ie++;
    sprintf((*vd).sde[ie], "    dataa    : in std_logic := '1';\n");ie++;
    sprintf((*vd).sde[ie], "    datab    : in std_logic := '1';\n");ie++;
    sprintf((*vd).sde[ie], "    datac    : in std_logic := '1';\n");ie++;
    sprintf((*vd).sde[ie], "    datad    : in std_logic := '1';\n");ie++;
    sprintf((*vd).sde[ie], "    aclr     : in std_logic := '0';\n");ie++;
    sprintf((*vd).sde[ie], "    ena      : in std_logic := '1';\n");ie++;
    sprintf((*vd).sde[ie], "    combout  : out std_logic;\n");ie++;
    sprintf((*vd).sde[ie], "    regout   : out std_logic);\n");ie++;
    sprintf((*vd).sde[ie], "end component;\n");ie++;
  }else if(strcmp(dev_name,"cyclone")==0){
    sprintf((*vd).sde[ie], "component cyclone_lcell                         \n");ie++;
    sprintf((*vd).sde[ie], "  generic                                       \n");ie++;
    sprintf((*vd).sde[ie], "  (                                             \n");ie++;
    sprintf((*vd).sde[ie], "    operation_mode : string := \"normal\";      \n");ie++;
    sprintf((*vd).sde[ie], "    synch_mode     : string := \"off\";         \n");ie++;
    sprintf((*vd).sde[ie], "    register_cascade_mode : string := \"off\";  \n");ie++;
    sprintf((*vd).sde[ie], "    sum_lutc_input : string := \"datac\";       \n");ie++;
    sprintf((*vd).sde[ie], "    lut_mask       : string := \"0000\";        \n");ie++;
    sprintf((*vd).sde[ie], "    power_up       : string := \"low\";         \n");ie++;
    sprintf((*vd).sde[ie], "    cin0_used      : string := \"false\";       \n");ie++;
    sprintf((*vd).sde[ie], "    cin1_used      : string := \"false\";       \n");ie++;
    sprintf((*vd).sde[ie], "    cin_used       : string := \"false\";       \n");ie++;
    sprintf((*vd).sde[ie], "    output_mode    : string := \"comb_and_reg\" \n");ie++;
    sprintf((*vd).sde[ie], "  );                                            \n");ie++;
    sprintf((*vd).sde[ie], "  port (clk: in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "    dataa  : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "    datab  : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "    datac  : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "    datad  : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "--  aclr   : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "--  aload  : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "--  sclr   : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "--  sload  : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "    ena    : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "--  cin    : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "--  cin0   : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "--  cin1   : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "--  inverta   : in std_logic := '0';     \n");ie++;
    sprintf((*vd).sde[ie], "--  regcascin : in std_logic := '0';     \n");ie++;
    sprintf((*vd).sde[ie], "    combout   : out std_logic;           \n");ie++;
    sprintf((*vd).sde[ie], "    regout    : out std_logic);          \n");ie++;
    sprintf((*vd).sde[ie], "--  cout   : out std_logic;              \n");ie++;
    sprintf((*vd).sde[ie], "--  cout0  : out std_logic;              \n");ie++;
    sprintf((*vd).sde[ie], "--  cout1  : out std_logic);             \n");ie++;
    sprintf((*vd).sde[ie], "end component;                           \n");ie++;
  }else if(strcmp(dev_name,"stratix")==0){
    sprintf((*vd).sde[ie], "component stratix_lcell                         \n");ie++;
    sprintf((*vd).sde[ie], "  generic                                       \n");ie++;
    sprintf((*vd).sde[ie], "  (                                             \n");ie++;
    sprintf((*vd).sde[ie], "    operation_mode : string := \"normal\";      \n");ie++;
    sprintf((*vd).sde[ie], "    synch_mode     : string := \"off\";         \n");ie++;
    sprintf((*vd).sde[ie], "    register_cascade_mode : string := \"off\";  \n");ie++;
    sprintf((*vd).sde[ie], "    sum_lutc_input : string := \"datac\";       \n");ie++;
    sprintf((*vd).sde[ie], "    lut_mask       : string := \"0000\";        \n");ie++;
    sprintf((*vd).sde[ie], "    power_up       : string := \"low\";         \n");ie++;
    sprintf((*vd).sde[ie], "    cin0_used      : string := \"false\";       \n");ie++;
    sprintf((*vd).sde[ie], "    cin1_used      : string := \"false\";       \n");ie++;
    sprintf((*vd).sde[ie], "    cin_used       : string := \"false\";       \n");ie++;
    sprintf((*vd).sde[ie], "    output_mode    : string := \"comb_and_reg\" \n");ie++;
    sprintf((*vd).sde[ie], "  );                                            \n");ie++;
    sprintf((*vd).sde[ie], "  port (clk: in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "    dataa  : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "    datab  : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "    datac  : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "    datad  : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "--  aclr   : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "--  aload  : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "--  sclr   : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "--  sload  : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "    ena    : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "--  cin    : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "--  cin0   : in std_logic := '0';        \n");ie++;
    sprintf((*vd).sde[ie], "--  cin1   : in std_logic := '1';        \n");ie++;
    sprintf((*vd).sde[ie], "--  inverta   : in std_logic := '0';     \n");ie++;
    sprintf((*vd).sde[ie], "--  regcascin : in std_logic := '0';     \n");ie++;
    sprintf((*vd).sde[ie], "    combout   : out std_logic;           \n");ie++;
    sprintf((*vd).sde[ie], "    regout    : out std_logic);          \n");ie++;
    sprintf((*vd).sde[ie], "--  cout   : out std_logic;              \n");ie++;
    sprintf((*vd).sde[ie], "--  cout0  : out std_logic;              \n");ie++;
    sprintf((*vd).sde[ie], "--  cout1  : out std_logic);             \n");ie++;
    sprintf((*vd).sde[ie], "end component;                           \n");ie++;
  }
  sprintf((*vd).sde[ie], "begin                                      \n");ie++;
  sprintf((*vd).sde[ie], "ifgen0: if (FF=0) generate\n");ie++;
  sprintf((*vd).sde[ie], "  u0: %s_lcell generic map(lut_mask=>MASK)\n",dev_name);ie++;
  sprintf((*vd).sde[ie], "      port map(dataa=>x(0),datab=>x(1),datac=>x(2),datad=>x(3),\n");ie++;
  sprintf((*vd).sde[ie], "               clk=>clk,combout=>z);\n");ie++;
  sprintf((*vd).sde[ie], "end generate;\n");ie++;
  sprintf((*vd).sde[ie], "ifgen1: if (FF>0) generate\n");ie++;
  sprintf((*vd).sde[ie], "  u0: %s_lcell generic map(lut_mask=>MASK)\n",dev_name);ie++;
  sprintf((*vd).sde[ie], "      port map(dataa=>x(0),datab=>x(1),datac=>x(2),datad=>x(3),\n");ie++;
  sprintf((*vd).sde[ie], "               clk=>clk,regout=>z);\n");ie++;
  sprintf((*vd).sde[ie], "end generate;\n");ie++;
  sprintf((*vd).sde[ie], "end rtl;\n");ie++;

  // Logic Cell in the ARITHMETIC MODE
  sprintf((*vd).sde[ie], "\n" );ie++;
  sprintf((*vd).sde[ie], "--+--------+----------------------+\n");ie++;
  sprintf((*vd).sde[ie], "--| ci,y,x | z       , co         |\n");ie++;
  sprintf((*vd).sde[ie], "--+--------+----------------------+\n");ie++;
  sprintf((*vd).sde[ie], "--|  0,0,0 | MASK(8) , MASK(0)    |\n");ie++;
  sprintf((*vd).sde[ie], "--|  0,0,1 | MASK(9) , MASK(1)    |\n");ie++;
  sprintf((*vd).sde[ie], "--|  0,1,0 | MASK(10), MASK(2)    |\n");ie++;
  sprintf((*vd).sde[ie], "--|  0,1,1 | MASK(11), MASK(3)    |\n");ie++;
  sprintf((*vd).sde[ie], "--|  1,0,0 | MASK(12), MASK(4)    |\n");ie++;
  sprintf((*vd).sde[ie], "--|  1,0,1 | MASK(13), MASK(5)    |\n");ie++;
  sprintf((*vd).sde[ie], "--|  1,1,0 | MASK(14), MASK(6)    |\n");ie++;
  sprintf((*vd).sde[ie], "--|  1,1,1 | MASK(15), MASK(7)    |\n");ie++;
  sprintf((*vd).sde[ie], "--+--------+----------------------+\n");ie++;
  sprintf((*vd).sde[ie], "library ieee;\n" );ie++;
  sprintf((*vd).sde[ie], "use ieee.std_logic_1164.all;\n" );ie++;
  sprintf((*vd).sde[ie], "library wysiwyg;\n" );ie++;
  sprintf((*vd).sde[ie], "use wysiwyg.%s_components.all;\n",dev_name);ie++;
  sprintf((*vd).sde[ie], "\n" );ie++;
  sprintf((*vd).sde[ie], "entity pg_lcell_ari is\n");ie++;
  sprintf((*vd).sde[ie], "  generic(MASK: string  := \"96E8\";\n");ie++;
  sprintf((*vd).sde[ie], "            FF: integer := 0);\n");ie++;
  sprintf((*vd).sde[ie], "    port(x,y,ci : in std_logic;\n");ie++;
  sprintf((*vd).sde[ie], "         z,co : out std_logic;\n");ie++;
  sprintf((*vd).sde[ie], "         clk : in std_logic);\n");ie++;
  sprintf((*vd).sde[ie], "end pg_lcell_ari;\n");ie++;
  sprintf((*vd).sde[ie], "\n" );ie++;
  sprintf((*vd).sde[ie], "architecture rtl of pg_lcell_ari is\n");ie++;
  sprintf((*vd).sde[ie], "\n" );ie++;
  if((strcmp(dev_name,"apex20k")==0)||(strcmp(dev_name,"apex20ke")==0)){
    sprintf((*vd).sde[ie], "component %s_lcell\n",dev_name);ie++;
    sprintf((*vd).sde[ie], "  generic (operation_mode   : string := \"arithmetic\";\n");ie++;
    sprintf((*vd).sde[ie], "    output_mode : string    := \"comb_and_reg\";\n");ie++;
    sprintf((*vd).sde[ie], "    packed_mode : string    := \"false\";\n");ie++;
    sprintf((*vd).sde[ie], "    lut_mask    : string    := \"96E8\";\n");ie++;
    sprintf((*vd).sde[ie], "    power_up : string       := \"low\";\n");ie++;
    sprintf((*vd).sde[ie], "    cin_used : string       := \"true\");\n");ie++;
    sprintf((*vd).sde[ie], "  port (clk  : in std_logic := '0';\n");ie++;
    sprintf((*vd).sde[ie], "    dataa    : in std_logic := '1';\n");ie++;
    sprintf((*vd).sde[ie], "    datab    : in std_logic := '1';\n");ie++;
    sprintf((*vd).sde[ie], "--  datac    : in std_logic := '1';\n");ie++;
    sprintf((*vd).sde[ie], "--  datad    : in std_logic := '1';\n");ie++;
    sprintf((*vd).sde[ie], "--  aclr     : in std_logic := '0';\n");ie++;
    sprintf((*vd).sde[ie], "    ena      : in std_logic := '1';\n");ie++;
    sprintf((*vd).sde[ie], "    cin      : in std_logic := '0';\n");ie++;
    sprintf((*vd).sde[ie], "    combout  : out std_logic;\n");ie++;
    sprintf((*vd).sde[ie], "    regout   : out std_logic;\n");ie++;
    sprintf((*vd).sde[ie], "    cout     : out std_logic);\n");ie++;
    sprintf((*vd).sde[ie], "end component;\n");ie++;
  }else if(strcmp(dev_name,"cyclone")==0){
    sprintf((*vd).sde[ie], "component cyclone_lcell                         \n");ie++;
    sprintf((*vd).sde[ie], "   generic                                      \n");ie++;
    sprintf((*vd).sde[ie], "  (                                             \n");ie++;
    sprintf((*vd).sde[ie], "   operation_mode    : string := \"arithmetic\";\n");ie++;
    sprintf((*vd).sde[ie], "   synch_mode : string := \"off\";              \n");ie++;
    sprintf((*vd).sde[ie], "   register_cascade_mode   : string := \"off\"; \n");ie++;
    sprintf((*vd).sde[ie], "-- sum_lutc_input : string := \"datac\";        \n");ie++;
    sprintf((*vd).sde[ie], "   lut_mask       : string := \"96E8\";         \n");ie++;
    sprintf((*vd).sde[ie], "   power_up       : string := \"low\";          \n");ie++;
    sprintf((*vd).sde[ie], "   cin0_used      : string := \"false\";        \n");ie++;
    sprintf((*vd).sde[ie], "   cin1_used      : string := \"false\";        \n");ie++;
    sprintf((*vd).sde[ie], "   cin_used       : string := \"true\";         \n");ie++;
    sprintf((*vd).sde[ie], "   output_mode    : string := \"comb_and_reg\"  \n");ie++;
    sprintf((*vd).sde[ie], "  );                                            \n");ie++;
    sprintf((*vd).sde[ie], " port (clk : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "   dataa   : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "   datab   : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "-- datac   : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "-- datad   : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "-- aclr    : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- aload   : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- sclr    : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- sload   : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "   ena     : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "   cin     : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- cin0    : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- cin1    : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "-- inverta : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- regcascin : in std_logic := '0';  \n");ie++;
    sprintf((*vd).sde[ie], "   combout   : out std_logic;        \n");ie++;
    sprintf((*vd).sde[ie], "   regout    : out std_logic;        \n");ie++;
    sprintf((*vd).sde[ie], "   cout   : out std_logic);          \n");ie++;
    sprintf((*vd).sde[ie], "-- cout0  : out std_logic;           \n");ie++;
    sprintf((*vd).sde[ie], "-- cout1  : out std_logic);          \n");ie++;
    sprintf((*vd).sde[ie], "end component;                       \n");ie++;
  }else if(strcmp(dev_name,"stratix")==0){
    sprintf((*vd).sde[ie], "component stratix_lcell                         \n");ie++;
    sprintf((*vd).sde[ie], "   generic                                      \n");ie++;
    sprintf((*vd).sde[ie], "  (                                             \n");ie++;
    sprintf((*vd).sde[ie], "   operation_mode    : string := \"arithmetic\";\n");ie++;
    sprintf((*vd).sde[ie], "   synch_mode : string := \"off\";              \n");ie++;
    sprintf((*vd).sde[ie], "   register_cascade_mode   : string := \"off\"; \n");ie++;
    sprintf((*vd).sde[ie], "-- sum_lutc_input : string := \"datac\";        \n");ie++;
    sprintf((*vd).sde[ie], "   lut_mask       : string := \"96E8\";         \n");ie++;
    sprintf((*vd).sde[ie], "   power_up       : string := \"low\";          \n");ie++;
    sprintf((*vd).sde[ie], "   cin0_used      : string := \"false\";        \n");ie++;
    sprintf((*vd).sde[ie], "   cin1_used      : string := \"false\";        \n");ie++;
    sprintf((*vd).sde[ie], "   cin_used       : string := \"true\";         \n");ie++;
    sprintf((*vd).sde[ie], "   output_mode    : string := \"comb_and_reg\"  \n");ie++;
    sprintf((*vd).sde[ie], "  );                                            \n");ie++;
    sprintf((*vd).sde[ie], " port (clk : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "   dataa   : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "   datab   : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "-- datac   : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "-- datad   : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "-- aclr    : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- aload   : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- sclr    : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- sload   : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "   ena     : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "   cin     : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- cin0    : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- cin1    : in std_logic := '1';    \n");ie++;
    sprintf((*vd).sde[ie], "-- inverta : in std_logic := '0';    \n");ie++;
    sprintf((*vd).sde[ie], "-- regcascin : in std_logic := '0';  \n");ie++;
    sprintf((*vd).sde[ie], "   combout   : out std_logic;        \n");ie++;
    sprintf((*vd).sde[ie], "   regout    : out std_logic;        \n");ie++;
    sprintf((*vd).sde[ie], "   cout   : out std_logic);          \n");ie++;
    sprintf((*vd).sde[ie], "-- cout0  : out std_logic;           \n");ie++;
    sprintf((*vd).sde[ie], "-- cout1  : out std_logic);          \n");ie++;
    sprintf((*vd).sde[ie], "end component;                       \n");ie++;
  }
  sprintf((*vd).sde[ie], "begin                                    \n");ie++;
  sprintf((*vd).sde[ie], "                                         \n");ie++;
  sprintf((*vd).sde[ie], "ifgen0: if (FF=0) generate\n");ie++;
  sprintf((*vd).sde[ie], "  u0: %s_lcell generic map(lut_mask=>MASK) \n",dev_name);ie++;
  sprintf((*vd).sde[ie], "      port map(dataa=>x,datab=>y,cin=>ci,combout=>z,cout=>co,clk=>clk);\n");ie++;
  sprintf((*vd).sde[ie], "end generate;\n");ie++;
  sprintf((*vd).sde[ie], "ifgen1: if (FF>0) generate\n");ie++;
  sprintf((*vd).sde[ie], "  u0: %s_lcell generic map(lut_mask=>MASK) \n",dev_name);ie++;
  sprintf((*vd).sde[ie], "      port map(dataa=>x,datab=>y,cin=>ci,regout=>z,cout=>co,clk=>clk);\n");ie++;
  sprintf((*vd).sde[ie], "end generate;\n");ie++;


  sprintf((*vd).sde[ie], "\n");ie++;
  sprintf((*vd).sde[ie], "end rtl;\n");ie++;

  (*vd).ie = ie;
}
  
