#include<stdio.h>
#include "pgpgc2.h"

/***** from http://www.hidecnet.ne.jp/~sinzan/tips/c *******************/

char *StrShift( char *String, size_t nShift )
{
    char *start = String;
    char *stop  = String + strlen( String );
    memmove( start + nShift, start, stop-start+1 );
    return String + nShift;

}//StrShift

char *StrReplace( char *String, const char *From, const char *To )
{
       int   nToLen;
       int   nFromLen;
       int   nShift;
       char *start;
       char *stop;
       char *p;
       
       nToLen   = strlen( To );
       nFromLen = strlen( From );
       nShift   = nToLen - nFromLen;
       start    = String;
       stop     = String + strlen( String );

       while( NULL != ( p = (char*)strstr( start, From ) ) )
       {
          start = StrShift( p + nFromLen, nShift );
          stop  = stop + nShift;
          memmove( p, To, nToLen );
       }
       return String;

}//StrReplace

/***********************************/
	
void itobc(idata,sdata,nbit)
int idata;
char sdata[];
int nbit;
{
  int i,itmp;
  strcpy(sdata,"");
  for(i=0;i<nbit;i++){
    itmp =0x1&(idata>>(nbit-1-i));
    if(itmp == 1) strcat(sdata,"1");
    if(itmp == 0) strcat(sdata,"0");
  }
}


void generate_pg_pipe(vd)
struct vhdl_description *vd;
{

  int ii,i,ivmp,i0;
  static char sd[20000][STRLEN];
  char sdtmp[STRLEN];
  FILE *fp,*fopen();

  ii = 0;

    /*  header */

  sprintf(sd[ii], "/*                                                                  \n" );ii++;
  sprintf(sd[ii], "   Emulator top structure generated by                              \n" );ii++;
  sprintf(sd[ii], "     pgpgc2 : ver 0.0, Sep 9 2003                                   \n" );ii++;
  sprintf(sd[ii], "     Toshiyuki Fukushige                                            \n" );ii++;
  sprintf(sd[ii], "*/                                                                  \n" );ii++;
  sprintf(sd[ii], "#include <stdio.h>                                                  \n" );ii++;
  sprintf(sd[ii], "#include <math.h>                                                   \n" );ii++;
  sprintf(sd[ii], "                                                                    \n" );ii++;    

    /* function */

  for(i=0;i<(*vd).ifunc;i++) sprintf(sd[i+ii],"%s",(*vd).sdfunc[i]);
  ii += (*vd).ifunc;
  sprintf(sd[ii], "{                                                                   \n" );ii++;

    /* define statement */

  sprintf(sd[ii], "  int i,j;                                                          \n" );ii++;

  for(i=0;i<(*vd).idef;i++){
    int iflag,j;
    iflag = 0;
    for(j=0;j<i;j++){
      if(strcmp((*vd).sddef[i],(*vd).sddef[j])==0) iflag=1;
    }
    if(iflag==0){
      strcpy(sd[ii],"  ");
      sprintf(sdtmp,"%s",(*vd).sddef[i]);
      strcat(sd[ii],sdtmp);
      ii++;
    }
  }
  sprintf(sd[ii], "                                                                    \n" );ii++;

    /* constant */

  for(i=0;i<(*vd).ico;i++){
    strcpy(sd[i+ii],"  ");
    sprintf(sdtmp,"%s",(*vd).sdco[i]);
    strcat(sd[i+ii],sdtmp);
  }
  ii += (*vd).ico;
  sprintf(sd[ii], "                                                                    \n" );ii++;

    /* i-loop */

  sprintf(sd[ii], "  for(i=0;i<n;i++){                                               \n\n" );ii++;
  
    /* ip set */

  for(i=0;i<(*vd).iip;i++){
    strcpy(sd[i+ii],"    ");
    sprintf(sdtmp,"%s",(*vd).sdip[i]);
    strcat(sd[i+ii],sdtmp);
  }
  ii += (*vd).iip;
  sprintf(sd[ii], "                                                                    \n" );ii++;
  
    /* j-loop */    
  
  sprintf(sd[ii], "    for(j=0;j<n;j++){                                             \n\n" );ii++;
  
    /* jp set */

  for(i=0;i<(*vd).ijp;i++){
    strcpy(sd[i+ii],"      ");
    sprintf(sdtmp,"%s",(*vd).sdjp[i]);
    strcat(sd[i+ii],sdtmp);
  }
  ii += (*vd).ijp;
  sprintf(sd[ii], "                                                                    \n" );ii++;
  
  /* pipeline */

  for(i=0;i<(*vd).ipipe;i++){
    strcpy(sd[i+ii],"      ");
    sprintf(sdtmp,"%s",(*vd).sdpipe[i]);
    strcat(sd[i+ii],sdtmp);
  }
  ii += (*vd).ipipe;
  sprintf(sd[ii], "                                                                    \n" );ii++;
  
    /* end of j-loop */

  sprintf(sd[ii], "    }                                                                 \n\n" );ii++;

    /* fo set */

  for(i=0;i<(*vd).ifo;i++){
    strcpy(sd[i+ii],"    ");
    sprintf(sdtmp,"%s",(*vd).sdfo[i]);
    strcat(sd[i+ii],sdtmp);
  }
  ii += (*vd).ifo;
  sprintf(sd[ii], "                                                                    \n" );ii++;
  
    /* end of i-loop */

  sprintf(sd[ii], "  }                                                                   \n" );ii++;

    /* end of function */

  sprintf(sd[ii], "}                                                                   \n" );ii++;  
  
    /* print out */

  fp = fopen("pg_pipe.c","w");
  for(i=0;i<ii;i++) fprintf(fp,"%s",sd[i]);
  fclose(fp);

}


void ufix_conversion(psd,i,xufix,xreal,xscale,xoffset,nbit)
     char psd[][STRLEN];
     int *i;
     char xufix[];
     char xreal[];     
     char xscale[];
     char xoffset[];
     int nbit;
{
  int mask;
  if(nbit==32){
    sprintf(psd[*i],"%s = ((unsigned int) ((%s + %s) * %s + 0.5)) & 0xffffffff;\n",xufix,xreal,xoffset,xscale);
  }else{
    mask  = (1<<nbit) - 1; 
    sprintf(psd[*i],"%s = ((unsigned int) ((%s + %s) * %s + 0.5)) & 0x%x ;\n",xufix,xreal,xoffset,xscale,mask);
  }
  (*i)++;
}

void fix_conversion(psd,i,xufix,xreal,xscale,nbit)
     char psd[][STRLEN];
     int *i;
     char xufix[];
     char xreal[];     
     char xscale[];
     int nbit;
{
  int mask;
  if(nbit==32){
    sprintf(psd[*i],"%s = ((int) (%s * %s + 0.5)) & 0xffffffff;\n",xufix,xreal,xscale);
  }else{
    mask  = (1<<nbit) - 1; 
    sprintf(psd[*i],"%s = ((int) (%s * %s + 0.5)) & 0x%x ;\n",xufix,xreal,xscale,mask);
  }
  (*i)++;
}

void log_conversion(psd,i,xlog,xreal,xscale,nbit,nman)
     char psd[][STRLEN];
     int *i;
     char xlog[];
     char xreal[];     
     char xscale[];
     int nbit;
     int nman;     
{
  int mask,bsnz,bsnzm;

  mask  = (1<<(nbit-2)) - 1; 
  bsnz =  1<<(nbit-2);
  bsnzm =  3<<(nbit-2);  
  sprintf(psd[*i],"if(%s == 0.0){                                         \n",xreal);(*i)++;
  sprintf(psd[*i],"  %s = 0;                                                \n",xlog);(*i)++;
  sprintf(psd[*i],"}else if(%s > 0.0){                                    \n",xreal);(*i)++;
  sprintf(psd[*i],"  %s = (((int)(pow(2.0,%d.0)*log(%s*%s)/log(2.0))) & 0x%x) | 0x%x;\n",xlog,nman,xreal,xscale,mask,bsnz);(*i)++;
  sprintf(psd[*i],"}else{                                                 \n");(*i)++;
  sprintf(psd[*i],"  %s = (((int)(pow(2.0,%d.0)*log(-%s*%s)/log(2.0))) & 0x%x) | 0x%x;\n",xlog,nman,xreal,xscale,mask,bsnzm);(*i)++;
  sprintf(psd[*i],"}                                                      \n");(*i)++;
  
}

main(argc,argv)
int argc;
char *argv[];
{
	char isdata[STRLEN];
	char isdata2[STRLEN];
	static char sdata[100][STRLEN];
	char *p;
	int i,j,ii,jj;
	FILE *fp,*fopen();
        static struct vhdl_description sd;
	    int itmp;
	    char stmp[STRLEN];
	    int dtmp;

        sd.nvmp = 1;
	sd.npipe = 1;
        sd.ifunc = 0;
        sd.ipipe = 0;
        sd.idef = 0;	
	sd.ijp = sd.iip = sd.ifo = 0;
	
        if(argc!=2){
	  printf("pgpgc2 filename\n");
	  exit(0);
	}else{
  	  fp = fopen(argv[1],"r");
	}
	
	while(fgets(isdata,STRLEN,fp)!=NULL){	  
	  i = 0;
	  strcpy(isdata2,isdata);
	  p = (char*)strtok(isdata,"( ");
	  strcpy(sdata[i],p);
	  i++;
	  if((strcmp(sdata[0],"/JPSET")==0)||(strcmp(sdata[0],"/IPSET")==0)||(strcmp(sdata[0],"/FOSET")==0)){
	    StrReplace(isdata2,"pow(2.0,","pow(2.0");
	    p = (char*)strtok(isdata2,"( ");
	    strcpy(sdata[0],p);
	    i=1;
	    while((p = (char*)strtok(NULL, ",; "))!=NULL){
	      strcpy(sdata[i],p);
	      i++;
	    }
	    for(j=0;j<i;j++){
	      StrReplace(sdata[j],"pow(2.0","pow(2.0,");
	    }
	    StrReplace(sdata[i-1],"\n","");	      
	  }else{
	    while((p = (char*)strtok(NULL, ",(); "))!=NULL){
	      strcpy(sdata[i],p);
	      i++;
	    }
	  }
	  
	  /*	  for(j=0;j<i;j++) printf("%d %s\n",j,sdata[j]);*/
 
	  if(strcmp(sdata[0],"/NVMP")==0){
	    sscanf(sdata[1],"%d",&(sd.nvmp));
	    printf("nvmp %d\n",sd.nvmp);
	  }

	  if(strcmp(sdata[0],"/NPIPE")==0){
	    sscanf(sdata[1],"%d",&(sd.npipe));
	    printf("npipe %d\n",sd.npipe);
	  }

	  if((strcmp(sdata[0],"void")==0)||(strcmp(sdata[0],"int")==0)||(strcmp(sdata[0],"double")==0)){
	    strcpy(sd.sdfunc[sd.ifunc],isdata2);
	    (sd.ifunc)++;
	  }

	  if(strcmp(sdata[0],"pg_fix_addsub")==0){
	    if(strcmp(sdata[1],"SUB")==0){
	      sprintf(sd.sdpipe[sd.ipipe],"pg_fix_sub_%s(%s,%s,&%s);\n",sdata[5],sdata[2],sdata[3],sdata[4]);(sd.ipipe)++;
	    }
	    if(strcmp(sdata[1],"ADD")==0){
	      sprintf(sd.sdpipe[sd.ipipe],"pg_fix_add_%s(%s,%s,&%s);\n",sdata[5],sdata[2],sdata[3],sdata[4]);(sd.ipipe)++;
	    }
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[2]);(sd.idef)++;	    
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[3]);(sd.idef)++;
	  }

	  if(strcmp(sdata[0],"pg_log_muldiv")==0){
	    if(strcmp(sdata[1],"MUL")==0) strcpy(stmp,"mul");
	    if(strcmp(sdata[1],"DIV")==0) strcpy(stmp,"div");
	    if(strcmp(sdata[1],"SDIV")==0) strcpy(stmp,"sdiv");
            sprintf(sd.sdpipe[sd.ipipe],"pg_log_%s_%s(%s,%s,&%s);\n",stmp,sdata[5],sdata[2],sdata[3],sdata[4]);(sd.ipipe)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[2]);(sd.idef)++;	    
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[3]);(sd.idef)++;
	  }

	  if(strcmp(sdata[0],"pg_log_shift")==0){
	    dtmp = atoi(sdata[1]);
	    if(dtmp<0){
	      sprintf(stmp,"m%d",-dtmp);
	    }else{
	      sprintf(stmp,"%d",dtmp);	      
	    }
            sprintf(sd.sdpipe[sd.ipipe],"pg_log_shift_log%s_%s(%s,&%s);\n",sdata[4],stmp,sdata[2],sdata[3]);(sd.ipipe)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[2]);(sd.idef)++;	    
	  }

	  if(strcmp(sdata[0],"pg_pdelay")==0){
            sprintf(sd.sdpipe[sd.ipipe],"pg_pdelay_%s_np%s(%s,&%s);\n",sdata[3],sdata[4],sdata[1],sdata[2]);(sd.ipipe)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[1]);(sd.idef)++;
	  }

	  if(strcmp(sdata[0],"pg_conv_ftol")==0){
            sprintf(sd.sdpipe[sd.ipipe],"pg_conv_ftol_fix%s_log%s_man%s(%s,&%s);\n",sdata[3],sdata[4],sdata[5],sdata[1],sdata[2]);(sd.ipipe)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[1]);(sd.idef)++;
	  }

	  if(strcmp(sdata[0],"pg_conv_ltof")==0){
            sprintf(sd.sdpipe[sd.ipipe],"pg_conv_ltof_log%s_man%s_fix%s(%s,&%s);\n",sdata[3],sdata[4],sdata[5],sdata[1],sdata[2]);(sd.ipipe)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[1]);(sd.idef)++;
	  }

	  if(strcmp(sdata[0],"pg_log_add")==0){
            sprintf(sd.sdpipe[sd.ipipe],"pg_log_add_log%s_man%s(%s,%s,&%s);\n",sdata[4],sdata[5],sdata[1],sdata[2],sdata[3]);(sd.ipipe)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[1]);(sd.idef)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[2]);(sd.idef)++;	    
	  }

	  if(strcmp(sdata[0],"pg_log_unsigned_add")==0){
            sprintf(sd.sdpipe[sd.ipipe],"pg_log_unsigned_add_log%s_man%s(%s,%s,&%s);\n",sdata[4],sdata[5],sdata[1],sdata[2],sdata[3]);(sd.ipipe)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[1]);(sd.idef)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[2]);(sd.idef)++;	    
	  }

	  if(strcmp(sdata[0],"pg_fix_accum")==0){
            sprintf(sd.sdpipe[sd.ipipe],"pg_fix_accum_f%s_s%s(%s,&%s);\n",sdata[3],sdata[4],sdata[1],sdata[2]);(sd.ipipe)++;	    
            sprintf(sd.sddef[sd.idef],"long long int %s;\n",sdata[1]);(sd.idef)++;
	  }
	    
	  if(strcmp(sdata[0],"pg_rundelay")==0){
	  }

	  if(strcmp(sdata[0],"pg_wtable")==0){
            sprintf(sd.sdpipe[sd.ipipe],"pg_wtable(%s,%s,%s,&%s);\n",sdata[3],sdata[4],sdata[1],sdata[2]);(sd.ipipe)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[1]);(sd.idef)++;
	  }

	  if(strcmp(sdata[0],"pg_dwtable")==0){
            sprintf(sd.sdpipe[sd.ipipe],"pg_dwtable(%s,%s,%s,&%s);\n",sdata[3],sdata[4],sdata[1],sdata[2]);(sd.ipipe)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[1]);(sd.idef)++;
	  }

	  if(strcmp(sdata[0],"/JPSET")==0){
	    StrReplace(sdata[5],"[]","[j]");
	    if(strcmp(sdata[6],"ufix")==0){
	      ufix_conversion(&(sd.sdjp),&(sd.ijp),sdata[1],sdata[5],sdata[8],sdata[9],atoi(sdata[7]));
	    }
	    if(strcmp(sdata[6],"fix")==0){
	      fix_conversion(&(sd.sdjp),&(sd.ijp),sdata[1],sdata[5],sdata[8],atoi(sdata[7]));
	    }
	    if(strcmp(sdata[6],"log")==0){
	      log_conversion(&(sd.sdjp),&(sd.ijp),sdata[1],sdata[5],sdata[9],atoi(sdata[7]),atoi(sdata[8]));
	    }
	  }

	  if(strcmp(sdata[0],"/IPSET")==0){
	    StrReplace(sdata[2],"[]","[i]");
	    if(strcmp(sdata[3],"ufix")==0){
	      ufix_conversion(&(sd.sdip),&(sd.iip),sdata[1],sdata[2],sdata[5],sdata[6],atoi(sdata[4]));
	    }
	    if(strcmp(sdata[3],"fix")==0){
	      fix_conversion(&(sd.sdip),&(sd.iip),sdata[1],sdata[2],sdata[5],atoi(sdata[4]));
	    }
	    if(strcmp(sdata[3],"log")==0){
	      log_conversion(&(sd.sdip),&(sd.iip),sdata[1],sdata[2],sdata[6],atoi(sdata[4]),atoi(sdata[5]));
	    }
	  }

	  if(strcmp(sdata[0],"/FOSET")==0){
	    StrReplace(sdata[2],"[]","[i]");
	    itmp = atoi(sdata[4]);  
            sprintf(sd.sdfo[sd.ifo],"%s = ((double)(%s<<%d))*%s/pow(2.0,%d.0);\n",sdata[2],sdata[1],64-itmp,sdata[5],64-itmp);(sd.ifo)++;
            sprintf(sd.sddef[sd.idef],"long long int %s;\n",sdata[1]);(sd.idef)++;
            sprintf(sd.sdip[sd.iip],"%s = 0;\n",sdata[1]);(sd.iip)++;
	  }

	  if(strcmp(sdata[0],"/VALSET")==0){
	    sscanf(sdata[2],"%x",&itmp);
            sprintf(sd.sdco[sd.ico],"%s = 0x%x;\n",sdata[1],itmp);(sd.ico)++;
            sprintf(sd.sddef[sd.idef],"int %s;\n",sdata[1]);(sd.idef)++;
	  }

	}

	fclose(fp);

	generate_pg_pipe(&sd);

}

     

		     
