/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* nbit   :   32-bit      */
/* ADDSUB :   SUB          */
#include<stdio.h>
void pg_fix_sub_32(int x,int y,int* z){
  unsigned int _x;
  unsigned int _y;
  int _z;
  _x = 0xFFFFFFFF&x;
  _y = 0xFFFFFFFF&y;
  _z = (int)(_x - _y);
  *z = 0xFFFFFFFF&_z;
}
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* nbit_fix   :   32-bit      */          
/* nbit_log   :   17-bit      */          
/* nbit_man   :   8-bit      */          
#include<stdio.h>                                                  
#include<math.h>                                                   
void pg_conv_ftol_fix32_log17_man8(int fixdata, int* logdata){                 
  int fixdata_msb=0;                                               
  int logdata_sign=0;                                              
  int fixdata_body=0;                                              
  int abs=0;                                                       
  int abs_decimal=0;                                               
  int logdata_nonzero=0;                                           
  int penc_out = 0; /* Output of penc */                           
  int table_adr = 0;                                               
  int table_overflow = 0;                                          
  int logdata_mantissa=0;                                          
  int logdata_exponent=0;                                          

  /* SIGN BIT */                                                   
  fixdata_msb = 0x1&(fixdata >>31);         
  logdata_sign = fixdata_msb;                                      

  /* ABSOLUTE */                                                   
  fixdata_body    = 0x7FFFFFFF & fixdata;        
  {                                                                
    int inv_fixdata_body=0;                                        
    inv_fixdata_body = 0x7FFFFFFF ^ fixdata_body;
    if(fixdata_msb == 0x1){                                        
      abs = 0x7FFFFFFF & (inv_fixdata_body + 1); 
    }else{                                                         
      abs = fixdata_body;                                          
    }                                                              
  }                                                                
  abs_decimal = 0x3FFFFFFF& abs;                 

  /* GENELATE NON-ZERO BIT (ALL BIT OR) */                                 
  if(abs != 0x0){ logdata_nonzero = 0x1; }else{ logdata_nonzero=0x0; }     

  { /* PRIORITY ENCODER */                                         
    int i;                                                         
    int count=0;                                                   
    for(i=31;i >=0;i--){                                           
        int buf;                                                   
        buf = 0x1 & (abs >>i);                                     
        if(buf == 0x1){ count = i; break;}                         
        count = i;                                                 
    }                                                              
    penc_out=count;                                                
  }                                                                
  penc_out = 0x1F & penc_out; /* 5-bit */
  
  /* SHIFTER */                                                                      
  {                                                                                  
    int seed=0;                                                                      
    if(penc_out>=10){                                         
      seed = abs_decimal;                                                            
      table_adr = 0x3FF & (seed>>(penc_out-10));
    }else{                                                                           
      seed = abs_decimal << 10;                               
      table_adr = 0x3FF & (seed>>penc_out);                         
    }                                                                                
  }                                                                                  
  
  /* TABLE */                                                                        
  /* TABLE INPUT WIDTH  = 10-bit */                           
  /* TABLE OUTPUT WIDTH = 8-bit */                             
  {                                                                                  
    int adr=0;                                                                       
    double adr_double=0.0;                                                           
    double data_double=0.0;                                                          
    int data;                                                                        
    adr = 0x3FF & table_adr;                                  
    adr_double =   ( ((double)adr) + 0.5 )/1024.000000;   
    data_double = 256.000000*(log(1.0 + adr_double))/log(2.0) + 0.5;
    data = (int)data_double;                                                         
    /* CHECK OVERFLOW */                                                             
    if((0x1&(data >>8))==0x1){                                   
      data = 0;                                                                      
      table_overflow = 1;   /* overflow flag */                                      
    }else{                                                                           
      table_overflow = 0;                                                            
    }                                                                                
    logdata_mantissa = 0xFF & data;                            
  }                                                                                  
  
  /* ADDER (GENERATE EXPONENT PART) */                                               
  logdata_exponent = 0x1F & (penc_out + table_overflow);  
  
  *logdata = logdata_sign << 16| logdata_nonzero << 15| logdata_exponent << 8| logdata_mantissa ;
  
  return;                                                          
}                                                                  
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* PIPELINE DELAY */
/* nbit   :   17-bit    */
/* npipe  :   8-stage  */
 
#include<stdio.h>                                
void pg_pdelay_17_np8(int indata, int* outdata){
  *outdata = 0x1FFFF&indata;      
  return;                                        
}          
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* UNSIGNED logarithmic shifter(power 2^[nshift]) */
/* nbit   :   17-bit      */ 
/* nshift :   1-bit      */         
/* --- [NOTE!] ---
   Input/Output width of this component is different !
     Input Width : 17-bit. [17-bit Signed Logarithmic Format] 
     Onput Width : 16-bit. [17-bit Unsigned Logarithmic Format without a sign bit.] */

/* --- [NOTE!] ---
   nshift must be 2, 1, -1 or -2. */

#include<stdio.h>                                        
void pg_log_shift_log17_1(int logimage_x, int* logimage_z){ 
  int x_sign=0;        /* Sign Flag:  1-bit (for debug)*/
  int x_nonzero=0;     /* NonZero Flag: 1-bit */         
  int x_body=0;        /* 15-bit */   
  int z=0;             /* 16-bit */   

  x_sign    = 0x1&(logimage_x>>16);  /* for debug */
  x_nonzero = 0x1&(logimage_x>>15);
  x_body    = 0x7FFF&logimage_x;    

  z = (x_nonzero <<15)|(0x7FFF&(x_body<<1));
  z &= 0xFFFF;
  *logimage_z = z;

  return;  
}          
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* PIPELINE DELAY */
/* nbit   :   17-bit    */
/* npipe  :   5-stage  */
 
#include<stdio.h>                                
void pg_pdelay_17_np5(int indata, int* outdata){
  *outdata = 0x1FFFF&indata;      
  return;                                        
}          
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* logarithmic UNSIGNED adder */                                   
/* nbit_log   :   17-bit      */          
/* nbit_man   :   8-bit      */          
/* --- [NOTE!] ---
   Input/Output width of this component is 16-bit.      */

#include<stdio.h>                                                  
#include<math.h>                                                   
void pg_log_unsigned_add_log17_man8(int logimage_x, int logimage_y, int* logimage_z){
  int signz=0;  /* 1-bit */                                        
  int x1=0;     /* 17-bit */                  
  int y1=0;     /* 17-bit */                  
  int xy=0;     /* 17-bit (x1 - y1) */        
  int yx=0;     /* 17-bit (y1 - x1) */        
  int yx_msb=0; /*  1-bit SIGN of yx */                            
  int x2=0; /* 16-bit output of Left-MUX  */
  int d0=0; /* 16-bit output of Right-MUX */
  int d0_low_part=0;    /* TABLE INPUT */                          
  int d0_high_part=0;   /* MUX Middle INPUT */                     
  int df=0;             /* MUX Middle OUTPUT */                    
  int table_data=0;     /* TABLE OUTPUT */                         
  int logimage_ZperX=0; /* Logimage of (Real)Z/X */                

  /* SIGN EVALUATION                      
          ----------------------------    
          nonz(X) | nonz(Y) -> sign(Z)    
          --------+-------------------    
             0    |   0     ->   0        
             0    |   1     -> sign(Y)    
             1    |   0     -> sign(X)    
             1    |   1     -> sign(X)    
          ----------------------------  */
  {
    int nonzx,nonzy,signx,signy;
    signx = (logimage_x>>16)&0x1;
    signy = (logimage_y>>16)&0x1;
    nonzx = (logimage_x>>15)&0x1;
    nonzy = (logimage_y>>15)&0x1;
    if(      (nonzx==0x0)&&(nonzy==0x0)){ signz = 0x0;   }
    else if((nonzx==0x0)&&(nonzy==0x1)){  signz = signy; }
    else if((nonzx==0x1)&&(nonzy==0x0)){  signz = signx; }
    else{ /*(nonzx==0x1)&&(nonzy==0x1) */ signz = signx; }
  }

  /* RESET FUNCTION */ 
  {
    int nonzx;
    int nonzy;
    nonzx = 0x1&(logimage_x>>15);
    nonzy = 0x1&(logimage_y>>15);
    if(nonzx == 0x0) logimage_x &= 0x0;
    if(nonzy == 0x0) logimage_y &= 0x0;
  }

  x1 = 0xFFFF&logimage_x; /* The MSB(17th-bit) is zero. */
  y1 = 0xFFFF&logimage_y; /* The MSB(17th-bit) is zero. */

  /* SUB (Y-X),(X-Y) */                                            
  yx = 0x1FFFF&(y1 - x1);                       
  xy = 0x1FFFF&(x1 - y1);                       

  yx_msb = 0x1 & (yx >>16);                 

  /* MUX Left */
  if(yx_msb==0x1){x2=0xFFFF&logimage_x;}else{x2=0xFFFF&logimage_y;}

  /* MUX Right */
  if(yx_msb==0x1){d0=0xFFFF&xy;}else{d0=0xFFFF&yx;}

  /* ===========================
     table input  = 12 bits                   
     table output = 9 bits                  
     =========================== */
  d0_low_part  = 0xFFF&d0;      /* 12-bit */
  d0_high_part = 0xF&(d0>>12); 

  /* MUX Middle */
  if(d0_high_part == 0x0){ df=0x1; }else{ df=0x0; }                

  /* TABLE LOG_ADD */
  {                                                                                     
    int table_adr = 0;                                                                  
    double D = 0.0;                                                                     
    double z_x = 0.0;                                                                   
    table_adr = d0_low_part; /* (logimage X) - (logimage Y) */                          
    D = ((double)table_adr+0.25)/256.000000;                              
    z_x = (log(1.0+pow(2.0,-1.0*D ))/log(2.0));   /* logimage[(Real)Z/X] */             
    z_x *= 256.000000;                                                    
    table_data = (int)(z_x+0.5);                                                        
    table_data &= 0x1FF;  /* TABLE OUTPUT : 9-bit */
  }                                                                                     

  /* MUX Last */
  if(df == 0x1){ logimage_ZperX = table_data; }else{ logimage_ZperX = 0;}

  /* ADDER :16-bit width */ 
  {                                                
    int add_out=0;                                 
    add_out = x2 + logimage_ZperX;                 
    add_out &= 0xFFFF;       
                   /* WITH SIGN-BIT (2002/07/26) */
    *logimage_z = (signz<<16) | add_out;
  }                                                

  return;  
}          
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* UNSIGNED logarithmic shifter(power 2^[nshift]) */
/* nbit   :   17-bit      */ 
/* nshift :   m1-bit      */         
/* --- [NOTE!] ---
   Input/Output width of this component is different !
     Input Width : 17-bit. [17-bit Signed Logarithmic Format] 
     Onput Width : 16-bit. [17-bit Unsigned Logarithmic Format without a sign bit.] */

/* --- [NOTE!] ---
   nshift must be 2, 1, -1 or -2. */

#include<stdio.h>                                        
void pg_log_shift_log17_m1(int logimage_x, int* logimage_z){ 
  int x_sign=0;        /* Sign Flag:  1-bit (for debug)*/
  int x_nonzero=0;     /* NonZero Flag: 1-bit */         
  int x_body=0;        /* 15-bit */   
  int z=0;             /* 16-bit */   

  x_sign    = 0x1&(logimage_x>>16);  /* for debug */
  x_nonzero = 0x1&(logimage_x>>15);
  x_body    = 0x7FFF&logimage_x;    

  z = (x_nonzero <<15)|(0x7FFF&(x_body>>1));
  z &= 0xFFFF;
  *logimage_z = z;

  return;  
}          
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* nbit   :   17-bit      */                  
/* MULDIV :   MUL          */                  
#include<stdio.h>                                                  
void pg_log_mul_17(int x,int y,int* z){                        
  int _signbit_x=0;                                                
  int _signbit_y=0;                                                
  int _signbit_z=0;                                                
  int _nonzbit_x=0;                                                
  int _nonzbit_y=0;                                                
  int _nonzbit_z=0;                                                
  int _x=0;                                                        
  int _y=0;                                                        
  int _z=0;                                                        
  _signbit_x = 0x1&(x >> 16);               
  _signbit_y = 0x1&(y >> 16);               
  _signbit_z = _signbit_x ^ _signbit_y;                            
  _nonzbit_x = 0x1&(x >> 15);               
  _nonzbit_y = 0x1&(y >> 15);               
  _nonzbit_z = _nonzbit_x & _nonzbit_y;                            
  _x = 0x7FFF&x;                              
  _y = 0x7FFF&y;                              
  _z = _x + _y;                                                  
  _z = 0x7FFF&_z;                           
  *z = _signbit_z << 16 | _nonzbit_z << 15 | _z;                                                           
  *z = 0x1FFFF&(*z);                              
  return;                                                          
}                                                                  
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* PIPELINE DELAY */
/* nbit   :   17-bit    */
/* npipe  :   12-stage  */
 
#include<stdio.h>                                
void pg_pdelay_17_np12(int indata, int* outdata){
  *outdata = 0x1FFFF&indata;      
  return;                                        
}          
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* nbit   :   17-bit      */                  
/* MULDIV :   DIV          */                  
#include<stdio.h>                                                  
void pg_log_div_17(int x,int y,int* z){                        
  int _signbit_x=0;                                                
  int _signbit_y=0;                                                
  int _signbit_z=0;                                                
  int _nonzbit_x=0;                                                
  int _nonzbit_y=0;                                                
  int _nonzbit_z=0;                                                
  int _x=0;                                                        
  int _y=0;                                                        
  int _z=0;                                                        
  _signbit_x = 0x1&(x >> 16);               
  _signbit_y = 0x1&(y >> 16);               
  _signbit_z = _signbit_x ^ _signbit_y;                            
  _nonzbit_x = 0x1&(x >> 15);               
  _nonzbit_y = 0x1&(y >> 15);               
  _nonzbit_z = _nonzbit_x & _nonzbit_y;                            
  _x = 0x7FFF&x;                              
  _y = 0x7FFF&y;                              
  _z = _x - _y;                                                  
  _z = 0x7FFF&_z;                           
  *z = _signbit_z << 16 | _nonzbit_z << 15 | _z;                                                           
  *z = 0x1FFFF&(*z);                              
  return;                                                          
}                                                                  
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* nbit_log   :   17-bit      */          
/* nbit_man   :   8-bit      */          
/* nbit_fix   :   57-bit      */          
#include<stdio.h>                                                  
#include<math.h>                                                   
void pg_conv_ltof_log17_man8_fix57(int logdata, long long int* fixdata){       
  int logdata_sign=0;                                              
  int logdata_nonzero=0;                                           
  int logdata_exponent=0;                                          
  int logdata_mantissa=0;                                          
  int fixdata_sign=0;                                              
  unsigned long long int fixdata_absolute=0;                       
  int table_adr=0;                                                 
  int table_data=0;                                                
  int shift_indata=0;                                              
  int shift_control=0;                                             

  /* VECTOR PREPARATION */                                         
  logdata_sign=0x1&(logdata>>16);     
  logdata_nonzero=0x1&(logdata>>15);     
  logdata_exponent=0x7F&(logdata>>8);       
  logdata_mantissa=0xFF&logdata;            

  /* SIGN BIT */                                                   
  fixdata_sign=logdata_sign;                                       

  /* TABLE */                                                      
  table_adr = logdata_mantissa;                                    
  {                                                                
    double x     = 0.0;                                            
    double y     = 0.0;                                            
    double depth = 256.000000;                     
    x = pow(2.0,((double)table_adr)/depth);                        
    y = (256.000000*(x-1.0)) +0.5; 
    table_data = (int)y;                                           
    table_data &= 0xFF;                    
  }                                                                

  /* MULTIPLEXOR */                                                
  {                                                                
    int muxout=0;                                                  
    if(logdata_nonzero == 0x1){                                    
      muxout = 0x1 << 8 | table_data;
    }else{                                                         
      muxout = 0x0;                                                
    }                                                              
    shift_indata = muxout;                                         
  }                                                                

  /* SHIFTER */                                                    
  shift_control = logdata_exponent;                                
  {                                                                
    unsigned long long int shift_out=0;                            
    unsigned long long int seed=0;                                 
    if(shift_control < 8*sizeof(long long int)){
      seed = ((unsigned long long int)shift_indata) << shift_control;
    }else{
      seed = 0x0LL;
    }
    shift_out = seed >> 8;   
    fixdata_absolute = 0x00FFFFFFFFFFFFFFULL & shift_out;   
  }                                                                

  *fixdata = (long long int)fixdata_sign << 56 | fixdata_absolute;

  return;                                                          
}                                                                  
/* Generated by PGPG module generateor       */
/* Copyright(c) 2001-2004 by Tsuyoshi Hamada */
/* Fixed-Point Accumulate Registor*/                          
/* nbit_fx(input)   :   57-bit      */
/* nbit_sx(register):   64-bit      */
/* --- [NOTE!] ---
   The format of input data is not the 2's complement one.
   MSB means a sign flag, and the other part means abusolute(not<0) integer. */

#include<stdio.h>                                                  
#include<math.h>                                                   
void pg_fix_accum_f57_s64(long long int fdata, long long int* sdata){ 
  long long int fx=0;     /* 57-bit */         
  long long int sx=0;     /* 64-bit */         
  long long int fx_sign=0;     /* 1-bit : sign flag of fdata */     
  long long int fx_abs=0;      /* 56-bit : absolute part of fdata */
  fx= 0x01FFFFFFFFFFFFFFULL&fdata;                             
  sx= 0xFFFFFFFFFFFFFFFFULL&(*sdata);                          
  fx_sign = 0x1&(fdata >>56);               
  fx_abs  = 0x00FFFFFFFFFFFFFFULL&fdata;                    
  if(fx_sign == 0x0){                                              
    sx = sx + fx_abs;                                              
  }else{                                                           
    sx = sx - fx_abs;                                              
  }                                                                

  *sdata = 0xFFFFFFFFFFFFFFFFULL&sx;
  return;  
}          
