/*                                                                  
   Emulator top structure generated by                              
     pgpgc2 : ver 0.0, Sep 9 2003                                   
     Toshiyuki Fukushige                                            
     Revised by Tsuyoshi Hamada                                     
*/                                                                  
#include <stdio.h>                                                  
#include <math.h>                                                   
                                                                    
void sph_pipeline_on_emulator(x,v,a,n,h,p,q,rho,divv,dudt)
        double x[][3];
        double v[][3];
        double a[][3];
        int n;
        double h[];
        double p[];
        double q[];
        double rho[];
        double divv[];
        double dudt[];
{                                                                   
  int i,j;                                                          
  long long int srho;
  long long int sdivv;
  long long int sax;
  long long int say;
  long long int saz;
  long long int sdudt;
  int rhoshift;
  int dshift;
  int fshift;
  int ushift;
  int xi;
  int xj;
  int yi;
  int yj;
  int zi;
  int zj;
  int xij;
  int yij;
  int zij;
  int dx;
  int dy;
  int dz;
  int x2;
  int y2;
  int z2;
  int x2y2;
  int z2r;
  int vxi;
  int vxj;
  int vyi;
  int vyj;
  int vzi;
  int vzj;
  int vxij;
  int vyij;
  int vzij;
  int dvx;
  int dvy;
  int dvz;
  int vxx;
  int vyy;
  int vzz;
  int vxy;
  int vzzr;
  int hi;
  int hir;
  int hii2;
  int hii3;
  int hii2r;
  int r2;
  int rhi2;
  int wi;
  int hii3r;
  int dwi;
  int hii5;
  int hj;
  int hjr;
  int hj2;
  int hj3;
  int hj2r;
  int rhj2;
  int wj;
  int hj3r;
  int dwj;
  int hj5;
  int whi;
  int whj;
  int dwhi;
  int dwhj;
  int w;
  int wrhos;
  long long int frho;
  int vdotr;
  int vdotrr;
  int dw;
  int vrdw0;
  int vrdw;
  long long int fdivv;
  int pj;
  int pi;
  int pir;
  int pjr;
  int qj;
  int qi;
  int qir;
  int qjr;
  int pij;
  int qij;
  int avij;
  int avdw0;
  int dxr;
  int avdw;
  int dyr;
  int dzr;
  int avdwx;
  int avdwy;
  int avdwz;
  long long int ax;
  long long int ay;
  long long int az;
  int vdotrrr;
  int avdw1;
  int dudt0;
  long long int fdudt;
                                                                    
  rhoshift = 0x1100;
  dshift = 0x1600;
  fshift = 0x1700;
  ushift = 0x1800;
                                                                    
  for(i=0;i<n;i++){                                               

    xi = ((unsigned int) ((x[i][0] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
    yi = ((unsigned int) ((x[i][1] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
    zi = ((unsigned int) ((x[i][2] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
    vxi = ((int) (v[i][0] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
    vyi = ((int) (v[i][1] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
    vzi = ((int) (v[i][2] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
    if(p[i] == 0.0){                                         
      pi = 0;                                                
    }else if(p[i] > 0.0){                                    
      pi = (((int)(pow(2.0,5.0)*log(p[i]*((1024.0)*2.0))/log(2.0))) & 0xfff) | 0x1000;
    }else{                                                 
      pi = (((int)(pow(2.0,5.0)*log(-p[i]*((1024.0)*2.0))/log(2.0))) & 0xfff) | 0x3000;
    }                                                      
    if(q[i] == 0.0){                                         
      qi = 0;                                                
    }else if(q[i] > 0.0){                                    
      qi = (((int)(pow(2.0,5.0)*log(q[i]*((1024.0)*(1024.0)))/log(2.0))) & 0xfff) | 0x1000;
    }else{                                                 
      qi = (((int)(pow(2.0,5.0)*log(-q[i]*((1024.0)*(1024.0)))/log(2.0))) & 0xfff) | 0x3000;
    }                                                      
    if(h[i] == 0.0){                                         
      hi = 0;                                                
    }else if(h[i] > 0.0){                                    
      hi = (((int)(pow(2.0,5.0)*log(h[i]*(pow(2.0,24)/16.0))/log(2.0))) & 0xfff) | 0x1000;
    }else{                                                 
      hi = (((int)(pow(2.0,5.0)*log(-h[i]*(pow(2.0,24)/16.0))/log(2.0))) & 0xfff) | 0x3000;
    }                                                      
    srho = 0;
    sdivv = 0;
    sax = 0;
    say = 0;
    saz = 0;
    sdudt = 0;
                                                                    
    for(j=0;j<n;j++){                                             

      xj = ((unsigned int) ((x[j][0] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
      yj = ((unsigned int) ((x[j][1] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
      zj = ((unsigned int) ((x[j][2] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
      vxj = ((int) (v[j][0] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
      vyj = ((int) (v[j][1] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
      vzj = ((int) (v[j][2] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
      if(h[j] == 0.0){                                         
        hj = 0;                                                
      }else if(h[j] > 0.0){                                    
        hj = (((int)(pow(2.0,5.0)*log(h[j]*(pow(2.0,24)/16.0))/log(2.0))) & 0xfff) | 0x1000;
      }else{                                                 
        hj = (((int)(pow(2.0,5.0)*log(-h[j]*(pow(2.0,24)/16.0))/log(2.0))) & 0xfff) | 0x3000;
      }                                                      
      if(p[j] == 0.0){                                         
        pj = 0;                                                
      }else if(p[j] > 0.0){                                    
        pj = (((int)(pow(2.0,5.0)*log(p[j]*(1024.0))/log(2.0))) & 0xfff) | 0x1000;
      }else{                                                 
        pj = (((int)(pow(2.0,5.0)*log(-p[j]*(1024.0))/log(2.0))) & 0xfff) | 0x3000;
      }                                                      
      if(q[j] == 0.0){                                         
        qj = 0;                                                
      }else if(q[j] > 0.0){                                    
        qj = (((int)(pow(2.0,5.0)*log(q[j]*((1024.0)*(1024.0)))/log(2.0))) & 0xfff) | 0x1000;
      }else{                                                 
        qj = (((int)(pow(2.0,5.0)*log(-q[j]*((1024.0)*(1024.0)))/log(2.0))) & 0xfff) | 0x3000;
      }                                                      
                                                                    
      pg_fix_sub_24(xi,xj,&xij);
      pg_fix_sub_24(yi,yj,&yij);
      pg_fix_sub_24(zi,zj,&zij);
      pg_conv_ftol_fix24_log14_man5(xij,&dx);
      pg_conv_ftol_fix24_log14_man5(yij,&dy);
      pg_conv_ftol_fix24_log14_man5(zij,&dz);
      pg_pdelay_14_np14(dx,&dxr);
      pg_pdelay_14_np14(dy,&dyr);
      pg_pdelay_14_np14(dz,&dzr);
      pg_log_shift_log14_1(dx,&x2);
      pg_log_shift_log14_1(dy,&y2);
      pg_log_shift_log14_1(dz,&z2);
      pg_log_unsigned_add_log14_man5(x2,y2,&x2y2);
      pg_pdelay_14_np3(z2,&z2r);
      pg_log_unsigned_add_log14_man5(x2y2,z2r,&r2);
      pg_fix_sub_14(vxi,vxj,&vxij);
      pg_fix_sub_14(vyi,vyj,&vyij);
      pg_fix_sub_14(vzi,vzj,&vzij);
      pg_conv_ftol_fix14_log14_man5(vxij,&dvx);
      pg_conv_ftol_fix14_log14_man5(vyij,&dvy);
      pg_conv_ftol_fix14_log14_man5(vzij,&dvz);
      pg_log_mul_14(dvx,dx,&vxx);
      pg_log_mul_14(dvy,dy,&vyy);
      pg_log_mul_14(dvz,dz,&vzz);
      pg_log_add_log14_man5(vxx,vyy,&vxy);
      pg_pdelay_14_np3(vzz,&vzzr);
      pg_log_add_log14_man5(vxy,vzzr,&vdotr);
      pg_pdelay_14_np11(hi,&hir);
      pg_log_shift_log14_1(hir,&hii2);
      pg_log_mul_14(hir,hii2,&hii3);
      pg_pdelay_14_np1(hii2,&hii2r);
      pg_log_mul_14(hii3,hii2r,&hii5);
      pg_pdelay_14_np1(hii3,&hii3r);
      pg_log_div_14(r2,hii2,&rhi2);
      pg_wtable(14,5,rhi2,&wi);
      pg_log_div_14(wi,hii3r,&whi);
      pg_dwtable(14,5,rhi2,&dwi);
      pg_log_div_14(dwi,hii5,&dwhi);
      pg_pdelay_14_np11(hj,&hjr);
      pg_log_shift_log14_1(hjr,&hj2);
      pg_log_mul_14(hjr,hj2,&hj3);
      pg_pdelay_14_np1(hj2,&hj2r);
      pg_log_mul_14(hj3,hj2r,&hj5);
      pg_pdelay_14_np1(hj3,&hj3r);
      pg_log_div_14(r2,hj2,&rhj2);
      pg_wtable(14,5,rhj2,&wj);
      pg_log_div_14(wj,hj3r,&whj);
      pg_dwtable(14,5,rhj2,&dwj);
      pg_log_div_14(dwj,hj5,&dwhj);
      pg_log_unsigned_add_log14_man5(whi,whj,&w);
      pg_log_unsigned_add_log14_man5(dwhi,dwhj,&dw);
      pg_log_sdiv_14(w,rhoshift,&wrhos);
      pg_conv_ltof_log14_man5_fix57(wrhos,&frho);
      pg_fix_accum_f57_s64(frho,&srho);
      pg_pdelay_14_np5(vdotr,&vdotrr);
      pg_log_mul_14(vdotrr,dw,&vrdw0);
      pg_log_sdiv_14(vrdw0,dshift,&vrdw);
      pg_conv_ltof_log14_man5_fix57(vrdw,&fdivv);
      pg_fix_accum_f57_s64(fdivv,&sdivv);
      pg_pdelay_14_np13(pj,&pjr);
      pg_pdelay_14_np13(pi,&pir);
      pg_log_mul_14(pir,pjr,&pij);
      pg_pdelay_14_np11(qj,&qjr);
      pg_pdelay_14_np11(qi,&qir);
      pg_log_unsigned_add_log14_man5(qir,qjr,&qij);
      pg_log_unsigned_add_log14_man5(pij,qij,&avij);
      pg_log_mul_14(dw,avij,&avdw0);
      pg_log_sdiv_14(avdw0,fshift,&avdw);
      pg_log_mul_14(dxr,avdw,&avdwx);
      pg_log_mul_14(dyr,avdw,&avdwy);
      pg_log_mul_14(dzr,avdw,&avdwz);
      pg_conv_ltof_log14_man5_fix57(avdwx,&ax);
      pg_conv_ltof_log14_man5_fix57(avdwy,&ay);
      pg_conv_ltof_log14_man5_fix57(avdwz,&az);
      pg_fix_accum_f57_s64(ax,&sax);
      pg_fix_accum_f57_s64(ay,&say);
      pg_fix_accum_f57_s64(az,&saz);
      pg_log_sdiv_14(avdw0,ushift,&avdw1);
      pg_pdelay_14_np2(vdotrr,&vdotrrr);
      pg_log_mul_14(vdotrrr,avdw1,&dudt0);
      pg_conv_ltof_log14_man5_fix57(dudt0,&fdudt);
      pg_fix_accum_f57_s64(fdudt,&sdudt);
                                                                    
    }                                                                 

    rho[i] = ((double)(srho<<0))*(M_1_PI/pow(2.0,76.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*pow(2.0,8.0))/pow(2.0,0.0);
    divv[i] = ((double)(sdivv<<0))*(M_1_PI/(pow(2.0,120.0)/3.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)/(pow(2.0,14)/4.0)*pow(2.0,48.0))/pow(2.0,0.0);
    a[i][0] = ((double)(sax<<0))*(M_1_PI/(pow(2.0,120.0)/3.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)/((1024.0)*(1024.0))*pow(2.0,56.0))/pow(2.0,0.0);
    a[i][1] = ((double)(say<<0))*(M_1_PI/(pow(2.0,120.0)/3.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)/((1024.0)*(1024.0))*pow(2.0,56.0))/pow(2.0,0.0);
    a[i][2] = ((double)(saz<<0))*(M_1_PI/(pow(2.0,120.0)/3.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)/((1024.0)*(1024.0))*pow(2.0,56.0))/pow(2.0,0.0);
    dudt[i] = ((double)(sdudt<<0))*(M_1_PI/(pow(2.0,120.0)/3.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)/(pow(2.0,14)/4.0)/((1024.0)*(1024.0))*pow(2.0,64.0))/pow(2.0,0.0);
                                                                    
  }                                                                   
}                                                                   
