/*                                                                  
   Interface Program for PG2                                        
     generated by pgpgi : ver 0.0, Dec 29 2004                      
     Toshiyuki Fukushige                                            
*/                                                                  
#include <stdio.h>                                                  
#include <math.h>                                                   
                                                                    
void sph_pipeline_on_emulator(x,v,a,n,h,p,q,rho,divv,dudt)
        double x[][3];
        double v[][3];
        double a[][3];
        int n;
        double h[];
        double p[];
        double q[];
        double rho[];
        double divv[];
        double dudt[];
{                                                                   
  int i,j,ii,nn;                                                    
  int devid,npipe;                                                  
  static int initflag=1;                                            
  int ndj,ni,nd,nword,retword;                                      
  unsigned int ipdata[2048];                                        
  unsigned int jpdata[2048];                                        
  unsigned int fodata[2048];                                        
  int xj;
  int yj;
  int zj;
  int vxj;
  int vyj;
  int vzj;
  int hj;
  int pj;
  int qj;
  int xi;
  int yi;
  int zi;
  int vxi;
  int vyi;
  int vzi;
  int pi;
  int qi;
  int hi;
  long long int srho;
  long long int sdivv;
  long long int sax;
  long long int say;
  long long int saz;
  long long int sdudt;
                                                                    
  devid = 0;                                                        
  npipe = 3;                                                 
                                                                    
  if(initflag == 1){                                                
    g6_init(devid);                                                 
    g6_send_fpga_data(devid,"pgfpga.ttf");                        
    initflag = 0;                                                   
  }                                                                 
                                                                    
  ndj = 2;                                                          
  ipdata[0] = 0x2000;                                               
  ipdata[1] = 0x2;                                                  
  ipdata[2] = ndj;                                                  
  ipdata[3] = 0x0;                                                  
  g6_set_ipdata(devid,ipdata);                                      
                                                                    
  ni = 3;                                                    
  nd = 12;                                                    
  ipdata[0] = 0x3002;                                               
  ipdata[1] = 0x2;                                                  
  ipdata[2] = ni;                                                   
  ipdata[3] = nd;                                                   
  g6_set_ipdata(devid,ipdata);                                      
                                                                    
  for(j=0;j<n;j++){                                             

    xj = ((unsigned int) ((x[j][0] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
    yj = ((unsigned int) ((x[j][1] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
    zj = ((unsigned int) ((x[j][2] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
    vxj = ((int) (v[j][0] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
    vyj = ((int) (v[j][1] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
    vzj = ((int) (v[j][2] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
    if(h[j] == 0.0){                                         
      hj = 0;                                                
    }else if(h[j] > 0.0){                                    
      hj = (((int)(pow(2.0,5.0)*log(h[j]*(pow(2.0,24)/16.0))/log(2.0))) & 0xfff) | 0x1000;
    }else{                                                 
      hj = (((int)(pow(2.0,5.0)*log(-h[j]*(pow(2.0,24)/16.0))/log(2.0))) & 0xfff) | 0x3000;
    }                                                      
    if(p[j] == 0.0){                                         
      pj = 0;                                                
    }else if(p[j] > 0.0){                                    
      pj = (((int)(pow(2.0,5.0)*log(p[j]*(1024.0))/log(2.0))) & 0xfff) | 0x1000;
    }else{                                                 
      pj = (((int)(pow(2.0,5.0)*log(-p[j]*(1024.0))/log(2.0))) & 0xfff) | 0x3000;
    }                                                      
    if(q[j] == 0.0){                                         
      qj = 0;                                                
    }else if(q[j] > 0.0){                                    
      qj = (((int)(pow(2.0,5.0)*log(q[j]*((1024.0)*(1024.0)))/log(2.0))) & 0xfff) | 0x1000;
    }else{                                                 
      qj = (((int)(pow(2.0,5.0)*log(-q[j]*((1024.0)*(1024.0)))/log(2.0))) & 0xfff) | 0x3000;
    }                                                      
                                                                    
    nword = 4;                                                      
    jpdata[0] = 0xffc00;                                            
    jpdata[1] = 3*j+2;                 
    jpdata[2] = 0x0 | ((0xffffff & xj) << 0) | ((0xff & yj) << 24) ;  
    jpdata[3] = 0x0 | (0xffff & (yj >> 8)) ;  
    g6_set_jpdata(devid,nword,jpdata);                              
                                                                    
    jpdata[1] = 3*j+1;                 
    jpdata[2] = 0x0 | ((0xffffff & zj) << 0) | ((0xff & vxj) << 24) ;  
    jpdata[3] = 0x0 | (0x3f & (vxj >> 8)) | ((0x3fff & vyj) << 6) ;  
    g6_set_jpdata(devid,nword,jpdata);                              
                                                                    
    jpdata[1] = 3*j+0;                 
    jpdata[2] = 0x0 | ((0x3fff & vzj) << 0) | ((0x3fff & hj) << 14) | ((0xf & pj) << 28) ;  
    jpdata[3] = 0x0 | (0x3ff & (pj >> 4)) | ((0x3fff & qj) << 10) ;  
    g6_set_jpdata(devid,nword,jpdata);                              
                                                                    
  }                                                                 

  for(i=0;i<n;i+=npipe){                                              
    if((i+npipe)>n){                                                  
      nn = n - i;                                                     
    }else{                                                            
      nn = npipe;                                                     
    }                                                                 
    for(ii=0;ii<nn;ii++){                                             
      xi = ((unsigned int) ((x[i+ii][0] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
      yi = ((unsigned int) ((x[i+ii][1] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
      zi = ((unsigned int) ((x[i+ii][2] + (16.0/2.0)) * (pow(2.0,24)/16.0) + 0.5)) & 0xffffff ;
      vxi = ((int) (v[i+ii][0] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
      vyi = ((int) (v[i+ii][1] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
      vzi = ((int) (v[i+ii][2] * (pow(2.0,14)/4.0) + 0.5)) & 0x3fff ;
      if(p[i+ii] == 0.0){                                         
        pi = 0;                                                
      }else if(p[i+ii] > 0.0){                                    
        pi = (((int)(pow(2.0,5.0)*log(p[i+ii]*((1024.0)*2.0))/log(2.0))) & 0xfff) | 0x1000;
      }else{                                                 
        pi = (((int)(pow(2.0,5.0)*log(-p[i+ii]*((1024.0)*2.0))/log(2.0))) & 0xfff) | 0x3000;
      }                                                      
      if(q[i+ii] == 0.0){                                         
        qi = 0;                                                
      }else if(q[i+ii] > 0.0){                                    
        qi = (((int)(pow(2.0,5.0)*log(q[i+ii]*((1024.0)*(1024.0)))/log(2.0))) & 0xfff) | 0x1000;
      }else{                                                 
        qi = (((int)(pow(2.0,5.0)*log(-q[i+ii]*((1024.0)*(1024.0)))/log(2.0))) & 0xfff) | 0x3000;
      }                                                      
      if(h[i+ii] == 0.0){                                         
        hi = 0;                                                
      }else if(h[i+ii] > 0.0){                                    
        hi = (((int)(pow(2.0,5.0)*log(h[i+ii]*(pow(2.0,24)/16.0))/log(2.0))) & 0xfff) | 0x1000;
      }else{                                                 
        hi = (((int)(pow(2.0,5.0)*log(-h[i+ii]*(pow(2.0,24)/16.0))/log(2.0))) & 0xfff) | 0x3000;
      }                                                      
      ipdata[0] = 0x0 | (ii<<4);                                     
      ipdata[1] = 9;                                            
      ipdata[2] = 0xffffff & xi;          
      ipdata[3] = 0xffffff & yi;          
      ipdata[4] = 0xffffff & zi;          
      ipdata[5] = 0x3fff & vxi;          
      ipdata[6] = 0x3fff & vyi;          
      ipdata[7] = 0x3fff & vzi;          
      ipdata[8] = 0x3fff & pi;          
      ipdata[9] = 0x3fff & qi;          
      ipdata[10] = 0x3fff & hi;          
      g6_set_ipdata(devid,ipdata);                                  
    }                                                               
                                                                    
    ipdata[0] = 0x4000;                                             
    ipdata[1] = 0x1;                                                
    ipdata[2] = 3*n;                                     
    g6_set_ipdata(devid,ipdata);                                    
                                                                    
    nword = ni * nd;                                                
    retword = g6_get_fodata(devid,nword,fodata);                    
                                                                    
    for(ii=0;ii<nn;ii++){                                           
      srho = ((long long int)fodata[1+nd*ii] << 32)
           | (long long int)fodata[0+nd*ii];                     
      sdivv = ((long long int)fodata[3+nd*ii] << 32)
           | (long long int)fodata[2+nd*ii];                     
      sax = ((long long int)fodata[5+nd*ii] << 32)
           | (long long int)fodata[4+nd*ii];                     
      say = ((long long int)fodata[7+nd*ii] << 32)
           | (long long int)fodata[6+nd*ii];                     
      saz = ((long long int)fodata[9+nd*ii] << 32)
           | (long long int)fodata[8+nd*ii];                     
      sdudt = ((long long int)fodata[11+nd*ii] << 32)
           | (long long int)fodata[10+nd*ii];                     
      rho[i] = ((double)(srho<<0))*(M_1_PI/pow(2.0,76.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*pow(2.0,8.0))/pow(2.0,0.0);
      divv[i] = ((double)(sdivv<<0))*(M_1_PI/(pow(2.0,120.0)/3.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)/(pow(2.0,14)/4.0)*pow(2.0,48.0))/pow(2.0,0.0);
      a[i][0] = ((double)(sax<<0))*(M_1_PI/(pow(2.0,120.0)/3.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)/((1024.0)*(1024.0))*pow(2.0,56.0))/pow(2.0,0.0);
      a[i][1] = ((double)(say<<0))*(M_1_PI/(pow(2.0,120.0)/3.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)/((1024.0)*(1024.0))*pow(2.0,56.0))/pow(2.0,0.0);
      a[i][2] = ((double)(saz<<0))*(M_1_PI/(pow(2.0,120.0)/3.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)/((1024.0)*(1024.0))*pow(2.0,56.0))/pow(2.0,0.0);
      dudt[i] = ((double)(sdudt<<0))*(M_1_PI/(pow(2.0,120.0)/3.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)*(pow(2.0,24)/16.0)/(pow(2.0,14)/4.0)/((1024.0)*(1024.0))*pow(2.0,64.0))/pow(2.0,0.0);
    }                                                               
                                                                    
  }                                                                   
}                                                                   
